final mockJson = {
  "dates": {"maximum": "2025-10-08", "minimum": "2025-08-27"},
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/ckT96Sn8r1IDNyIBJ1mDZ1Jh2kR.jpg",
      "genre_ids": [28, 80, 53],
      "id": 1267319,
      "original_language": "ko",
      "original_title": "사마귀",
      "overview":
          "La sociedad secreta de asesinos a sueldo se sume en el caos y surge una nueva generación de asesinos. Sin las viejas reglas, ¿quién se atreverá a reclamar las sombras?",
      "popularity": 410.6636,
      "poster_path": "/v1vs4RJyqzckfxPjyWN5zN1dEgH.jpg",
      "release_date": "2025-09-26",
      "title": "Mantis",
      "video": false,
      "vote_average": 6.202,
      "vote_count": 42,
    },
    {
      "adult": false,
      "backdrop_path": "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      "genre_ids": [16, 28, 14, 53],
      "id": 1311031,
      "original_language": "ja",
      "original_title": "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      "overview":
          "Tanjirō Kamado es un chico que se unió a una organización dedicada a cazar demonios después de que su hermana menor, Nezuko, fuera convertida. Mientras los miembros de la organización y los Pilares participaban en un programa de entrenamiento grupal, como preparación para la inminente batalla contra los demonios, Muzan Kibutsuji aparece en la Mansión Ubuyashiki. Con el jefe de la organización en peligro, Tanjirō y los Pilares corren hacia la mansión, pero son arrastrados a un espacio misterioso por obra de Kibutsuji. El lugar al que han caído Tanjirō y los cazadores es el bastión de los demonios: el Castillo Infinito. Así, el campo de batalla queda establecido para dar fin a la guerra entre humanos y demonios.",
      "popularity": 388.1548,
      "poster_path": "/iWLV12z9oexSRLz2WKyqCZbKoPA.jpg",
      "release_date": "2025-07-18",
      "title": "Demon Slayer: Kimetsu no Yaiba Castillo infinito",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 414,
    },
    {
      "adult": false,
      "backdrop_path": "/k6tdiMTO39RQj3dhfspuzprfoe0.jpg",
      "genre_ids": [80],
      "id": 941109,
      "original_language": "en",
      "original_title": "Play Dirty",
      "overview":
          "Parker es un experto ladrón, muy profesional en lo suyo, que elabora sus golpes con una ética de trabajo clara y directa. Junto con Grofield, Zen y un equipo experto, todos se toparán con un robo que los enfrenta a la mafia de Nueva York.",
      "popularity": 378.5993,
      "poster_path": "/iENIozg5IPgwl0lbPS7Vqz55LrX.jpg",
      "release_date": "2025-09-30",
      "title": "Juego sucio",
      "video": false,
      "vote_average": 6.347,
      "vote_count": 62,
    },
    {
      "adult": false,
      "backdrop_path": "/gDvlSJXM646Inc20dln7takAyUB.jpg",
      "genre_ids": [28, 27, 10752],
      "id": 1257009,
      "original_language": "en",
      "original_title": "Primitive War",
      "overview":
          "Vietnam. 1968. Una unidad de reconocimiento conocida como Escuadrón Buitre es enviada a un valle aislado de la jungla para descubrir el destino de un pelotón de Boina Verde desaparecido. Pronto descubren que no están solos.",
      "popularity": 356.7636,
      "poster_path": "/nWBqU5YXmDVJWWEDJ4u3ZSseNVL.jpg",
      "release_date": "2025-08-21",
      "title": "Primitive War",
      "video": false,
      "vote_average": 7.009,
      "vote_count": 56,
    },
    {
      "adult": false,
      "backdrop_path": "/yGByIyqgJerCw7AAphTrTAlrdkJ.jpg",
      "genre_ids": [28, 10752, 53, 36],
      "id": 1328803,
      "original_language": "en",
      "original_title": "Prisoner of War",
      "overview": "",
      "popularity": 354.7663,
      "poster_path": "/6paGLyOAvY95XxjfdiTcatwI7dJ.jpg",
      "release_date": "2025-09-19",
      "title": "Prisoner of War",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 54,
    },
    {
      "adult": false,
      "backdrop_path": "/fq8gLtrz1ByW3KQ2IM3RMZEIjsQ.jpg",
      "genre_ids": [27],
      "id": 1038392,
      "original_language": "en",
      "original_title": "The Conjuring: Last Rites",
      "overview":
          "En 1986, los investigadores paranormales, Ed y Lorraine Warren, salen de su retiro para investigar, junto con su hija adulta Judy y su compañero Tony, el caso Smurl, una entidad demoníaca más oscura.",
      "popularity": 236.4107,
      "poster_path": "/dyW5mX4wwDoZWgTYObx6pg9V0i9.jpg",
      "release_date": "2025-09-03",
      "title": "El Conjuro 4: Últimos ritos",
      "video": false,
      "vote_average": 6.6,
      "vote_count": 487,
    },
    {
      "adult": false,
      "backdrop_path": "/gZF6fDtE71Fi3AGcF0PSQAxCgE3.jpg",
      "genre_ids": [28],
      "id": 1552819,
      "original_language": "es",
      "original_title": "Assassin",
      "overview": "",
      "popularity": 213.8264,
      "poster_path": "/eNriIkhQusncgc5SipEgQUtrybO.jpg",
      "release_date": "2025-09-26",
      "title": "Assassin",
      "video": false,
      "vote_average": 2.333,
      "vote_count": 3,
    },
    {
      "adult": false,
      "backdrop_path": "/zpEWFNqoN8Qg1SzMMHmaGyOBTdW.jpg",
      "genre_ids": [28, 53, 80],
      "id": 1054867,
      "original_language": "en",
      "original_title": "One Battle After Another",
      "overview":
          "Cuando su malvado némesis resurge después de 16 años, una banda de ex revolucionarios se reúne para rescatar a la hija de uno de los suyos.",
      "popularity": 187.0053,
      "poster_path": "/iZ1499F6hYxDxiqioy8oSUaxipG.jpg",
      "release_date": "2025-09-23",
      "title": "Una batalla tras otra",
      "video": false,
      "vote_average": 7.781,
      "vote_count": 508,
    },
    {
      "adult": false,
      "backdrop_path": "/xR75PgmIxhS6ChjNUKgz4krC9MR.jpg",
      "genre_ids": [27, 9648, 53],
      "id": 957121,
      "original_language": "en",
      "original_title": "The Man in My Basement",
      "overview":
          "Charles Blakey, un afroamericano que vive en Sag Harbor, está estancado, sin suerte y a punto de perder su casa. En ese momento, un peculiar hombre de negocios blanco con acento europeo le ofrece alquilar su sótano durante el verano.",
      "popularity": 139.8249,
      "poster_path": "/1zpeH8wOrM8p2TTAmBetwhe2BIx.jpg",
      "release_date": "2025-09-12",
      "title": "The Man in My Basement",
      "video": false,
      "vote_average": 6.25,
      "vote_count": 12,
    },
    {
      "adult": false,
      "backdrop_path": "/w3Bi0wygeFQctn6AqFTwhGNXRwL.jpg",
      "genre_ids": [10751, 14, 10402, 35, 12, 16],
      "id": 803796,
      "original_language": "en",
      "original_title": "KPop Demon Hunters",
      "overview":
          "Cuando no están llenando estadios, las superestrellas del k‑pop Rumi, Mira y Zoey usan sus superpoderes secretos para proteger a sus fans de amenazas sobrenaturales.",
      "popularity": 136.6265,
      "poster_path": "/swQRKmW7RLhncPYHvM0RHz8b7bT.jpg",
      "release_date": "2025-06-20",
      "title": "Las guerreras k-pop",
      "video": false,
      "vote_average": 8.273,
      "vote_count": 1563,
    },
    {
      "adult": false,
      "backdrop_path": "/mEW9XMgYDO6U0MJcIRqRuSwjzN5.jpg",
      "genre_ids": [28, 53],
      "id": 1007734,
      "original_language": "en",
      "original_title": "Nobody 2",
      "overview":
          "El ex asesino Hutch Mansell lleva a su familia a unas nostálgicas vacaciones a un parque temático de una pequeña ciudad, solo para volver a verse arrastrado a la violencia cuando se enfrentan a un operador corrupto, un sheriff corrupto y un despiadado jefe criminal.",
      "popularity": 127.2374,
      "poster_path": "/qwdBh0102NX5fslXv3L9MSlXqKc.jpg",
      "release_date": "2025-08-13",
      "title": "Nadie 2",
      "video": false,
      "vote_average": 7.147,
      "vote_count": 730,
    },
    {
      "adult": false,
      "backdrop_path": "/79PNOxNXSe5e0bhEj11QJPlsdCN.jpg",
      "genre_ids": [14, 10751, 28, 12],
      "id": 1087192,
      "original_language": "en",
      "original_title": "How to Train Your Dragon",
      "overview":
          "En la agreste isla de Berk, donde vikingos y dragones han sido enemigos acérrimos durante generaciones, Hipo se distingue, desafiando siglos de tradición al entablar amistad con Desdentao, un temido dragón Furia Nocturna. Su improbable vínculo revela la verdadera naturaleza de los dragones, desafiando los cimientos de la sociedad vikinga.",
      "popularity": 112.9214,
      "poster_path": "/kjQXYc2Abhy3TBgAZGzJRhN1JaV.jpg",
      "release_date": "2025-06-06",
      "title": "Cómo entrenar a tu dragón",
      "video": false,
      "vote_average": 8.0,
      "vote_count": 1983,
    },
    {
      "adult": false,
      "backdrop_path": "/9KSboWOt09J72aMY4x8SS1IaOHK.jpg",
      "genre_ids": [16, 28, 12, 14],
      "id": 987400,
      "original_language": "es",
      "original_title": "Batman Azteca: Choque de imperios",
      "overview":
          "En la época del Imperio Azteca, Yohualli Coatl, un joven azteca, experimenta una tragedia cuando su padre y líder de la aldea, Toltecatzin, es asesinado por los conquistadores españoles. Yohualli escapa a Tenochtitlán para advertir al rey Moctezuma y a su sumo sacerdote, Yoka, del peligro inminente. Usando el templo de Tzinacan, el dios murciélago, como guarida, Yohualli entrena con su mentor y asistente, Acatzin, desarrollando equipo y armamento para enfrentar la invasión española, proteger el templo de Moctezuma y vengar la muerte de su padre.",
      "popularity": 112.7753,
      "poster_path": "/wpMaI2J3ISYZiaIWNkoA1lVb5LQ.jpg",
      "release_date": "2025-09-18",
      "title": "Batman Azteca: Choque de imperios",
      "video": false,
      "vote_average": 7.818,
      "vote_count": 85,
    },
    {
      "adult": false,
      "backdrop_path": "/dh0dLVLDLqUKhtytCFjkf3EHeJI.jpg",
      "genre_ids": [16, 28, 14],
      "id": 1218925,
      "original_language": "ja",
      "original_title": "チェンソーマン レゼ篇",
      "overview":
          "Denji se convirtió en \"Chainsaw Man\", un chico con corazón de diablo, y ahora es parte de los cazadores de demonios de la División Especial 4. Después de una cita con Makima, la mujer de sus sueños, Denji se refugia de la lluvia. Allí conoce a Reze, una chica que trabaja en un café.",
      "popularity": 110.844,
      "poster_path": "/1CfZCb56vWjq37uXtbKNMevMzwG.jpg",
      "release_date": "2025-09-19",
      "title": "Chainsaw Man – La Película: Arco de Reze",
      "video": false,
      "vote_average": 9.3,
      "vote_count": 9,
    },
    {
      "adult": false,
      "backdrop_path": "/bwP4UJZjjfAVOuTAWT8W8J2AKtG.jpg",
      "genre_ids": [53, 28],
      "id": 1450529,
      "original_language": "es",
      "original_title": "Gatillero",
      "overview":
          "Una cruda historia de tragedia y redención, contada a través de un único plano continuo. Rodada en la verdadera Isla Maciel, en las afueras de Buenos Aires, Argentina.",
      "popularity": 104.7551,
      "poster_path": "/moiLQPK2YjritOYG674DrWHvlgp.jpg",
      "release_date": "2025-06-12",
      "title": "Gatillero",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 9,
    },
    {
      "adult": false,
      "backdrop_path": "/6mkPrQiojzp88HNX5E4efhic5WN.jpg",
      "genre_ids": [10749, 18],
      "id": 1319965,
      "original_language": "en",
      "original_title": "All of You",
      "overview":
          "Laura y Simon son mejores amigos desde la universidad. Con los años, notaron que su relación es más que platónica. ¿Podrían, o deberían, arriesgarlo todo para explorar un amor que siempre existió?",
      "popularity": 94.0366,
      "poster_path": "/bC982oyPD6JCMa0V3Ve1vvaUVk3.jpg",
      "release_date": "2025-09-26",
      "title": "Todo de ti",
      "video": false,
      "vote_average": 6.419,
      "vote_count": 37,
    },
    {
      "adult": false,
      "backdrop_path": "/p4OIGFfVo3vbROMD1evVF0u14Rf.jpg",
      "genre_ids": [10749, 35],
      "id": 1289888,
      "original_language": "fr",
      "original_title": "French Lover",
      "overview":
          "Un actor hastiado conoce a una mesera sin suerte en París, y así comienza una inesperada historia de amor. ¿Su romance será más fuerte que la fama?",
      "popularity": 90.4131,
      "poster_path": "/s91yhwxBwDPfLUM7qTlJKzxzrV4.jpg",
      "release_date": "2025-09-25",
      "title": "French Lover",
      "video": false,
      "vote_average": 5.571,
      "vote_count": 70,
    },
    {
      "adult": false,
      "backdrop_path": "/uBB1aMga5ngZxsUQL5k36zeW3pB.jpg",
      "genre_ids": [27],
      "id": 1242011,
      "original_language": "en",
      "original_title": "Together",
      "overview":
          "Una pareja con problemas en su relación se muda al campo, donde descubren una cueva con una fuerza sobrenatural. Al beber agua de la cueva, comienzan a experimentar transformaciones físicas y emocionales que reflejan su codependencia.",
      "popularity": 89.3305,
      "poster_path": "/pp2ho64ah9W9jCCIHavXUCuqISr.jpg",
      "release_date": "2025-07-28",
      "title": "Together: Juntos hasta la muerte",
      "video": false,
      "vote_average": 7.212,
      "vote_count": 523,
    },
    {
      "adult": false,
      "backdrop_path": "/41043LV7mfluH8iXEUPVseCDAv5.jpg",
      "genre_ids": [80, 53, 35],
      "id": 1245993,
      "original_language": "en",
      "original_title": "Caught Stealing",
      "overview":
          "Nueva York, años 90. El ex jugador de béisbol Hank Thompson se ve inesperadamente envuelto en una peligrosa lucha por la supervivencia en medio de un submundo criminal peligroso.",
      "popularity": 85.2054,
      "poster_path": "/oyl44sKyNdWbVajTAz6oG6DZm8V.jpg",
      "release_date": "2025-08-26",
      "title": "Atrapado robando",
      "video": false,
      "vote_average": 7.0,
      "vote_count": 269,
    },
    {
      "adult": false,
      "backdrop_path": "/lB96EMr5A7Og81UhyldJvvy35r.jpg",
      "genre_ids": [10751, 35, 80, 12, 16],
      "id": 1175942,
      "original_language": "en",
      "original_title": "The Bad Guys 2",
      "overview":
          "Un genial equipo de animales que no respetan la ley, los ahora muy reformados Tipos Malos, se esfuerzan (mucho, muchísimo) en ser buenos, pero se ven envueltos involuntariamente en un golpe de envergadura mundial planeado por un inesperado grupo de criminales: las Tipas Malas.",
      "popularity": 83.9796,
      "poster_path": "/mZmnKDhIS2yNmtfzde5vtdCYzBF.jpg",
      "release_date": "2025-07-24",
      "title": "Los tipos malos 2",
      "video": false,
      "vote_average": 7.807,
      "vote_count": 423,
    },
  ],
  "total_pages": 286,
  "total_results": 5709,
};
